apiVersion: v1
kind: Pod
metadata:
    name: dbpedia.restricted.transe.embeddings
spec:
    securityContext:
        runAsUser: 4053
        fsGroup: 4053
    containers:
      - name: tf-container
        image: abhipec/iitg_kubernetes:p3_master_image_latest
        # command: ["ls"]
        command: [ "python3", "/data/OpenKE/train_dbpedia.py" ]
        resources:
            limits:
                nvidia.com/gpu: 1
        volumeMounts:
          - name: nfs-data
            mountPath: /data
    volumes:
      - name: nfs-data
        hostPath:
            path: /home/kubernetes/data/manan/
            type: Directory
    restartPolicy: Never
